### ISSUE TITLE
NWB file lacks required metadata for upload

### ISSUE THREAD

**Issue by nsdesai** [dandi/helpdesk#169] opened 2024-12-11 17:59 UTC
I am trying to upload NWB files to the DANDI (development) server. I keep getting an error saying that all required metadata are not included, but there is no indication of what is missing.

The original data were acquired in MATLAB and I converted them to NWB using this: https://neurodatawithoutborders.github.io/matnwb/

I can send an example NWB file if that would be helpful. (This interface won't let me attach NWB files.)

thanks,
Niraj

**Comment by kabilar** [comment] 2024-12-11 18:11
Hi @nsdesai, thanks for the report.  Is the error being returned from the website or the CLI?  Yes, please send us a file.  Google drive, dropbox, etc. would be fine.

Hi @h-mayorquin, could you please look into this issue once we receive the file?  Thanks.

**Comment by nsdesai** [comment] 2024-12-11 18:22
Thanks for the prompt reply!

I was trying to use NWB Guide to upload, even though I didn't use it to
convert.

An example NWB file can be found here:

https://drive.google.com/file/d/1LQuCNM9lQ4rtnIBGKsuDdiKI5NMF-Vjs/view?usp=drive_link

Thanks for your help.

Niraj

**Comment by h-mayorquin** [comment] 2024-12-11 18:47
Hi, @nsdesai 

You need to give me access to the file or make it public (I requested it already).

Also, if you can copy-paste the error that you are getting that would be useful for future users and for us to solve this quickly.

**Comment by nsdesai** [comment] 2024-12-11 18:54
![Screenshot 2024-12-11 135405](https://github.com/user-attachments/assets/7050f125-ccad-42c1-91aa-f386eb9c94f9)

Does this display correctly?

**Comment by h-mayorquin** [comment] 2024-12-11 19:04
Interesting, so I try to open your file and the problem is that your `CurrentClampSeries` does not have a gain (Error at the bottom)

This is marked as an optional argument in the schema:

https://nwb-schema.readthedocs.io/en/latest/format.html#sec-currentclampseries-src

So in theory, your file is correct but is not opening. This seems like a PyNWB but maybe they were changes recently. I will check with the pynwb team.


Error.

```


ConstructError: (root/acquisition/constant_response_001 GroupBuilder {'attributes': {'comments': 'no comments', 'description': 'no description', 'namespace': 'core', 'neurodata_type': 'CurrentClampSeries', 'object_id': 'a7bf8a22-ef0f-4b22-ae45-d5b1f03f3832', 'stimulus_description': 'constant_injection_001', 'sweep_number': 1}, 'groups': {}, 'datasets': {'bias_current': root/acquisition/constant_response_001/bias_current DatasetBuilder {'attributes': {}, 'data': 1e-11}, 'bridge_balance': root/acquisition/constant_response_001/bridge_balance DatasetBuilder {'attributes': {}, 'data': 20000000.0}, 'capacitance_compensation': root/acquisition/constant_response_001/capacitance_compensation DatasetBuilder {'attributes': {}, 'data': 1e-12}, 'data': root/acquisition/constant_response_001/data DatasetBuilder {'attributes': {'conversion': 1.0, 'offset': 0.0, 'resolution': -1.0, 'unit': 'volts'}, 'data': <HDF5 dataset \"data\": shape (50000,), type \"<f8\">}, 'timestamps': root/acquisition/constant_response_001/timestamps DatasetBuilder {'attributes': {'interval': 1, 'unit': 'seconds'}, 'data': <HDF5 dataset \"timestamps\": shape (15,), type \"<f8\">}}, 'links': {'electrode': root/acquisition/constant_response_001/electrode LinkBuilder {'builder': root/general/intracellular_ephys/elec0 GroupBuilder {'attributes': {'namespace': 'core', 'neurodata_type': 'IntracellularElectrode', 'object_id': 'c05e8a6f-ee55-4eed-81cf-ebd1abe9b090'}, 'groups': {}, 'datasets': {'cell_id': root/general/intracellular_ephys/elec0/cell_id DatasetBuilder {'attributes': {}, 'data': 'NBM/SI neuron'}, 'description': root/general/intracellular_ephys/elec0/description DatasetBuilder {'attributes': {}, 'data': 'patch clamp electrode (~5 MOhms)'}}, 'links': {'device': root/general/intracellular_ephys/elec0/device LinkBuilder {'builder': root/general/devices/National Instruments PCIe-6353 GroupBuilder {'attributes': {'namespace': 'core', 'neurodata_type': 'Device', 'object_id': '6eb5a13a-dc5d-4a48-ad16-fc252a98188a'}, 'groups': {}, 'datasets': {}, 'links': {}}}}}}}}, \"Could not construct CurrentClampSeries object due to: CurrentClampSeries.__init__: missing argument 'gain'\")"
}
```

**Comment by nsdesai** [comment] 2024-12-11 19:11
The original data were acquired using a custom MATLAB script and so I used
matNWB to convert (not pyNWB).

I thought I included everything from their example, but maybe I missed
"gain".

Let me try converting again and seeing what happens.

Niraj

**Comment by h-mayorquin** [comment] 2024-12-11 19:12
OK, so this was fixed recently:

https://github.com/NeurodataWithoutBorders/pynwb/pull/1975

But then I get another error that your timestamps do not have a time zone. Can you add that as well? 

This is the error that I get with the latest version of the inspector:

```
 'data': '2023-07-26T17:37:13.000000'}, 'timestamps_reference_time': root/timestamps_reference_time DatasetBuilder {'attributes': {}, 'data': '2023-07-26T17:37:13.000000'}}, 'links': {}}, "Could not construct NWBFile object due to: 'timestamps_reference_time' must be a timezone-aware datetime object.")
```

**Comment by nsdesai** [comment] 2024-12-11 19:25
I added a time zone. Here is a link:

https://drive.google.com/file/d/1xz5h8b_jJ1RNN4vpTlL3koFnl-eOFOZT/view?usp=sharing

**Comment by nsdesai** [comment] 2024-12-11 19:33
I should add that I've been using this as a template:

https://matnwb.readthedocs.io/en/latest/pages/tutorials/icephys.html

So to add a time zone, I simply added a "Time Zone" argument to session_start_time and specified "local."

**Comment by h-mayorquin** [comment] 2024-12-11 19:43
Hi, so this file can be opened with pynwb (which is progress) but you still have many issues to solve with the nwbinspector:

The issues marked as critical should be solved before the file can be uploaded. Have you tried putting this file in the guide, I think ti should show you some similar output right?

```


**************************************************
NWBInspector Report Summary

Timestamp: 2024-12-11 13:42:35.684966-06:00
Platform: Linux-6.8.0-49-generic-x86_64-with-glibc2.39
NWBInspector version: 0.6.1

Found 66 issues over 1 files:
       1 - PYNWB_VALIDATION
      30 - CRITICAL
      35 - BEST_PRACTICE_SUGGESTION
**************************************************


0  PYNWB_VALIDATION
===================

0.0  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: SweepTable/sweep_number - 'None' object at location 'general/intracellular_ephys/sweep_table/sweep_number'
       Message: incorrect type - expected 'uint32', got 'float64'

1  CRITICAL
===========

1.1  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_015'
       Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.2  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_014'
       Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.3  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_013'
       Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.4  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_012'
       Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.5  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_011'
       Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.6  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_010'
       Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.7  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_009'
       Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.8  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_008'
       Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.9  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_007'
       Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.10  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_006'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.11  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_005'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.12  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_004'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.13  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_003'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.14  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_002'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.15  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_001'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.16  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_015'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.17  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_014'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.18  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_013'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.19  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_012'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.20  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_011'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.21  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_010'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.22  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_009'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.23  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_008'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.24  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_007'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.25  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_006'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.26  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_005'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.27  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_004'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.28  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_003'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.29  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_002'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

1.30  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_timestamps_match_first_dimension - 'CurrentClampSeries' object at location '/acquisition/constant_response_001'
        Message: The length of the first dimension of data (50000) does not match the length of timestamps (15).

2  BEST_PRACTICE_SUGGESTION
===========================

2.31  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'Device' object at location '/general/devices/National Instruments PCIe-6353'
        Message: Description is missing.

2.32  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_015'
        Message: Description ('no description') is a placeholder.

2.33  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_014'
        Message: Description ('no description') is a placeholder.

2.34  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_013'
        Message: Description ('no description') is a placeholder.

2.35  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_012'
        Message: Description ('no description') is a placeholder.

2.36  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_011'
        Message: Description ('no description') is a placeholder.

2.37  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_010'
        Message: Description ('no description') is a placeholder.

2.38  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_009'
        Message: Description ('no description') is a placeholder.

2.39  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_008'
        Message: Description ('no description') is a placeholder.

2.40  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_007'
        Message: Description ('no description') is a placeholder.

2.41  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_006'
        Message: Description ('no description') is a placeholder.

2.42  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_005'
        Message: Description ('no description') is a placeholder.

2.43  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_004'
        Message: Description ('no description') is a placeholder.

2.44  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_003'
        Message: Description ('no description') is a placeholder.

2.45  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_002'
        Message: Description ('no description') is a placeholder.

2.46  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampStimulusSeries' object at location '/stimulus/presentation/constant_injection_001'
        Message: Description ('no description') is a placeholder.

2.47  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_015'
        Message: Description ('no description') is a placeholder.

2.48  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_014'
        Message: Description ('no description') is a placeholder.

2.49  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_013'
        Message: Description ('no description') is a placeholder.

2.50  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_012'
        Message: Description ('no description') is a placeholder.

2.51  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_011'
        Message: Description ('no description') is a placeholder.

2.52  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_010'
        Message: Description ('no description') is a placeholder.

2.53  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_009'
        Message: Description ('no description') is a placeholder.

2.54  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_008'
        Message: Description ('no description') is a placeholder.

2.55  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_007'
        Message: Description ('no description') is a placeholder.

2.56  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_006'
        Message: Description ('no description') is a placeholder.

2.57  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_005'
        Message: Description ('no description') is a placeholder.

2.58  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_004'
        Message: Description ('no description') is a placeholder.

2.59  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_003'
        Message: Description ('no description') is a placeholder.

2.60  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_002'
        Message: Description ('no description') is a placeholder.

2.61  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_description - 'CurrentClampSeries' object at location '/acquisition/constant_response_001'
        Message: Description ('no description') is a placeholder.

2.62  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_experimenter_form - 'NWBFile' object at location '/'
        Message: The name of experimenter 'FL' does not match any of the accepted DANDI forms: 'LastName, Firstname', 'LastName, FirstName MiddleInitial.' or 'LastName, FirstName, MiddleName'.

2.63  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_keywords - 'NWBFile' object at location '/'
        Message: Metadata /general/keywords is missing.

2.64  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_doi_publications - 'NWBFile' object at location '/'
        Message: Metadata /general/related_publications 'Feng et al., J. Comp. Neurol. (2024) PMID: 39576005' does not start with 'doi: ###' and is not an external 'doi' link.

2.65  MACAQUE_CHOL_NBM_FL_20230726T173713.nwb: check_subject_age - 'Subject' object at location '/general/subject'
        Message: Subject age, '7', does not follow ISO 8601 duration format, e.g. 'P2Y' for 2 years or 'P23W' for 23 weeks. You may also specify a range using a '/' separator, e.g., 'P1D/P3D' for an age range somewhere from 1 to 3 days. If you cannot specify the upper bound of the range, you may leave the right side blank, e.g., 'P90Y/' means 90 years old or older.

```

**Comment by nsdesai** [comment] 2024-12-11 20:12
It might take me a while to address these errors. I will let you know as soon as I do.

thanks for your help

**Comment by nsdesai** [comment] 2024-12-11 20:52
Inching ever closer ...

I fixed the errors except for some of the ones that are  marked "Can safely be ignored." I can deal with those later.

Now I can see the data using the Explore option in Guide. Everything seems to be there.

But using the Upload option, I now get a new error:

![Screenshot 2024-12-11 154742](https://github.com/user-attachments/assets/299ded9c-342c-4ba4-99fe-eda835483b2e)

This is a link to a revised file:

https://drive.google.com/file/d/1lQCXaalvLX2SuXZetn6vRc8Hy09nUGlD/view?usp=sharing

**Comment by h-mayorquin** [comment] 2024-12-11 21:29
This is a guide problem. I am not very familiar with it, any ideas @bendichter ?

**Comment by rly** [comment] 2024-12-11 22:07
The `session_id` in this file is `"BLA-projecting NBM/SI neuron from animal M24 on 26/07/2023"`. It looks like NWB GUIDE (or Neuroconv or DANDI) is replacing the "/" in the session ID with "\\" when renaming the file before upload, and therefore the file cannot be found. DANDI uses the following format for file names: `{dandiset_id}/sub-{subject_id}/sub-{subject_id}_ses-{session_id}.nwb` so a "/" in the session ID (or subject ID) would cause problems unless handled in a special way. I'll run some quick tests.

**Comment by rly** [comment] 2024-12-11 22:08
In the meantime, a quick workaround @nsdesai is to remove the "/" from your session IDs.

**Comment by nsdesai** [comment] 2024-12-11 22:09
Thanks, I will try that.

**Comment by nsdesai** [comment] 2024-12-11 22:40
Thank you! That worked.

Thanks also, @h-mayorquin , for your help this afternoon.

I should be able to upload all our data now (fingers crossed).

-- Niraj

**Comment by bendichter** [comment] 2024-12-12 07:28
We should create a check for this in the inspector

**Closed** 2024-12-12 08:02 UTC
